# Generated by Django 3.2 on 2023-04-18 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20230417_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='shows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stream.show'),
        ),
    ]
